host: 0.0.0.0
port: "9871"
password: my_password
session_secret: BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDkh9h2fhfUVuS9jZ8uVbhV3vC5AWX39IVU
buttons: [{name: mute discord, display_name: Mic Mute Discord, shell_command: "",
    keys: [m], logo: meet.png, shift: false, rshift: false, ctrl: true, rctrl: false,
    alt: true, ralt: false}, {name: apex, display_name: Start Apex Legends, shell_command: 'cmd
      /C start steam://rungameid/1172470', keys: [], logo: apex-logo.png, shift: false,
    rshift: false, ctrl: false, rctrl: false, alt: false, ralt: false}, {name: aa,
    display_name: Start Apex Legends, shell_command: 'cmd /C start steam://rungameid/1172470',
    keys: [], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Valorant_logo_-_pink_color_version.svg/1280px-Valorant_logo_-_pink_color_version.svg.png',
    shift: false, rshift: false, ctrl: false, rctrl: false, alt: false, ralt: false},
  {name: bb, display_name: Start Apex Legends, shell_command: 'cmd /C start steam://rungameid/1172470',
    keys: [], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/LEGO_logo.svg/500px-LEGO_logo.svg.png',
    shift: false, rshift: false, ctrl: false, rctrl: false, alt: false, ralt: false},
  {name: cc, display_name: Start Apex Legends, shell_command: 'cmd /C start steam://rungameid/1172470',
    keys: [], logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1024px-Microsoft_logo.svg.png',
    shift: false, rshift: false, ctrl: false, rctrl: false, alt: false, ralt: false}]
