host: "0.0.0.0"
port: "9871"
password: "my_password"
buttons:
  - 0:
    name: "mute discord"
    display_name: "Mic Mute Discord"
    keys: ["m"]
    shift: false
    rshift: false
    logo: "mute.png"
    ctrl: true
    rctrl: false
    alt: true
    ralt: false
  - 1:
    name: "apex"
    display_name: "Run Apex"
    logo: "apex-logo.png"
    shell_command: "cmd /C start steam://rungameid/1172470"
