name: Verify PrismaController Integrity

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1
    - name: Ubuntu dep update
      run: sudo apt-get update && sudo apt-get install gcc libxapp-dev libgtk-3-dev libayatana-appindicator3-dev
    - name: Install
      run: go install ./...
    - name: Tidy
      run: go mod tidy ./...
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
